### ISSUE TITLE
Can not sync new page from notion

### ISSUE THREAD

**Issue by WooodHead** [younho9/TIL#37]
Hi, younho9

I failed to make workflows working, did I miss anything?

This is what I did:

1. fork TIL repo.
2. duplicat notion databse from your database url: https://www.notion.so/107dc84223664f60b21a61f55b2700a4?v=5b277ec8bc5e4d3b854d065f9b1d1c89
3. setup secrets:
NOTION_TOKEN: *****
DATABASE_URL: my notion database url duplicated from yours.
4. change workflow config file for testing:
```
on:
  pull_request:
  push:
    branches:
      - main
```
5. add a new row in database for testing, main category -> CS
6. push for testing
7. workflow triggered but no new docs created.

Thanks for your great work.

**Comment by younho9** [comment]
Hello, WooodHead 👋

Explore the `narkdown.config.json` file in your repository and check `statusColumnName` and `currentStatus`.
The post that `statusColumnName` in the notion database is set to `currentStatus` is target to synchronization.

<img width="366" alt="스크린샷 2021-03-08 오후 8 35 50" src="https://user-images.githubusercontent.com/48426991/110316319-e5bae500-804d-11eb-9e2f-295e96913727.png">

**Comment by WooodHead** [comment]
Thank you younho9, it works now.
